spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/IdeaProjects/TPO_10/linkDB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl